spring:
  application:
    name: app_musik
  datasource:
    url: jdbc:mysql://localhost:3306/app_musik?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081


